#ifndef FZX_SETTINGS_HPP_
#define FZX_SETTINGS_HPP_

const float MINIMUM_VELOCITY_FOR_AWAKING = .5f;
const float MINIMUM_ANGULAR_VELOCITY_FOR_AWAKING = .5f;

const float PENETRATION_SEPERATION_PERCENTAGE = .5;
const float PENETRATION_SLOP = 0.01;

#endif /*FZX_SETTINGS_HPP_*/
